/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function MyComponent(props) {
  return (
    <div className="bg-white flex flex-col">
      <div className="bg-slate-950 self-stretch flex w-full flex-col items-stretch pl-20 pr-16 py-11 max-md:max-w-full max-md:px-5">
        <div className="flex w-full justify-between gap-5 ml-3.5 pr-7 items-start max-md:max-w-full max-md:flex-wrap max-md:pr-5">
          <div className="items-stretch flex justify-between gap-5 mt-5">
            <div className="text-white text-base font-medium leading-6 grow whitespace-nowrap">
              Home
            </div>
            <div className="items-stretch flex justify-between gap-2">
              <div className="text-white text-base font-medium leading-6 grow whitespace-nowrap">
                Model
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c39864743e1307d584fe8984bbf7dbc137f00ffa21825380437022e34957c772?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
              />
            </div>
            <div className="items-stretch flex justify-between gap-2">
              <div className="text-white text-base font-medium leading-6 grow whitespace-nowrap">
                Be a Partner
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/4097b4bf60bf7ffc3fa1af1492411806170862f95f5750aa5e8ddaa97fab41fb?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
              />
            </div>
            <div className="items-stretch flex justify-between gap-2">
              <div className="text-white text-base font-medium leading-6">
                More
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/23af5743255ea7151565bec537b10b9d12dbafcad318ce23683c858ffffa09f6?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
              />
            </div>
          </div>
          <div className="self-stretch flex items-center justify-between gap-5">
            <div className="text-white text-base font-medium leading-6 my-auto">
              Login
            </div>
            <div className="text-white text-right text-base font-semibold leading-6 whitespace-nowrap justify-center items-stretch bg-indigo-500 self-stretch grow px-4 py-3 rounded-xl">
              Join Our Discord
            </div>
          </div>
        </div>
        <div className="ml-3.5 mt-24 mb-1.5 max-md:max-w-full max-md:mt-10">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[55%] max-md:w-full max-md:ml-0">
              <div className="flex flex-col my-auto max-md:max-w-full max-md:mt-10">
                <div className="text-white text-6xl font-semibold leading-[68px] self-stretch max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
                  Empowering Trades with Our Capital 🔥
                </div>
                <div className="text-white text-lg leading-7 self-stretch mt-5 max-md:max-w-full">
                  Global Reach, Local Support: Funding Your Trading Dreams Up to
                  $300,000
                </div>
                <div className="text-white text-right text-lg font-semibold leading-6 justify-center items-stretch bg-indigo-500 mt-9 px-6 py-4 rounded-xl self-start max-md:px-5">
                  Get up to $300,000 funds 🙌
                </div>
                <div className="items-center self-stretch flex justify-between gap-5 mt-28 px-px max-md:max-w-full max-md:flex-wrap max-md:mt-10">
                  <div className="items-stretch self-stretch flex justify-between gap-2.5">
                    <div className="text-white text-4xl font-medium leading-[62px] grow whitespace-nowrap">
                      195+
                    </div>
                    <div className="text-white text-sm leading-5 self-center my-auto">
                      Countries <br />
                      Covered
                    </div>
                  </div>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/d87001ebfc2c52e255e7f91fc87c738003e870b8b93bf16abd32cd302542fca9?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-[0.39] object-contain object-center w-[15px] overflow-hidden shrink-0 max-w-full my-auto"
                  />
                  <div className="items-stretch self-stretch flex justify-between gap-2.5">
                    <div className="text-white text-4xl font-medium leading-[62px] grow whitespace-nowrap">
                      $51M+
                    </div>
                    <div className="text-white text-sm leading-5 self-center my-auto">
                      Total <br />
                      Payout
                    </div>
                  </div>
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/d87001ebfc2c52e255e7f91fc87c738003e870b8b93bf16abd32cd302542fca9?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-[0.39] object-contain object-center w-[15px] overflow-hidden shrink-0 max-w-full my-auto"
                  />
                  <div className="items-stretch self-stretch flex justify-between gap-0">
                    <div className="text-white text-4xl font-medium leading-[62px] grow whitespace-nowrap">
                      $51k+
                    </div>
                    <div className="text-white text-sm leading-5 self-center my-auto">
                      Funded <br />
                      Traders
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-stretch w-[45%] ml-5 max-md:w-full max-md:ml-0">
              <div className="grow max-md:max-w-full max-md:mt-10">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-[70%] max-md:w-full max-md:ml-0">
                    <div className="justify-center items-stretch bg-white flex grow flex-col w-full rounded-3xl max-md:max-w-full">
                      <img
                        loading="lazy"
                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fad71c667306d6770168cc0c11275c412a73d2040428fff5adadca5e693abf66?apiKey=877f25baca7641bea0898fac94c96e97&"
                        className="aspect-[0.75] object-contain object-center w-full overflow-hidden max-md:max-w-full"
                      />
                    </div>
                  </div>
                  <div className="flex flex-col items-stretch w-[30%] ml-5 max-md:w-full max-md:ml-0">
                    <div className="items-stretch shadow-2xl bg-white flex gap-2 w-full mt-14 px-2.5 py-2 rounded-[200px] max-md:mt-10">
                      <div className="text-white text-lg font-semibold leading-6 whitespace-nowrap aspect-square justify-center items-stretch p-1.5 rounded-[50%]">
                        🤘
                      </div>
                      <div className="text-gray-800 text-base font-semibold leading-7 self-center grow whitespace-nowrap my-auto">
                        Brand Promoter
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="items-stretch bg-indigo-500 self-stretch flex w-full flex-col justify-center py-px rounded max-md:max-w-full">
        <div className="items-stretch flex gap-0 px-5 py-2.5 max-md:max-w-full max-md:flex-wrap">
          <div className="text-teal-400 text-base items-stretch aspect-[1.9166666666666667] justify-center pr-7 py-1 border-r-zinc-200 border-r border-solid max-md:pr-5">
            (+0.28%)
          </div>
          <div className="flex gap-0 pl-4 pr-1 py-1 border-r-zinc-200 border-r border-solid items-start">
            <div className="self-stretch flex justify-between gap-2 pr-4 items-start">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/73a8c3fbc335b15befd98b066e218b822ec3cc66668c8ccf64f581cdd3130148?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-[18px] overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-white text-base font-bold self-stretch grow whitespace-nowrap">
                AUDCHF
              </div>
            </div>
            <div className="text-white text-base font-semibold mt-1">
              0.56708
            </div>
            <div className="items-stretch self-stretch flex justify-between gap-3 pr-2.5">
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                +0.00189
              </div>
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                (+0.33%)
              </div>
            </div>
          </div>
          <div className="items-center flex gap-px pl-4 pr-1 py-1 border-r-zinc-200 border-r border-solid">
            <div className="self-stretch flex justify-between gap-2 pr-5 items-start">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5f30b8ea1eb390c185837599d4dde128d1b64ad43cab3bc4d9db52e82c96cd98?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-[18px] overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-white text-base font-bold self-stretch grow whitespace-nowrap">
                AUDJPY
              </div>
            </div>
            <div className="text-white text-base font-semibold my-auto">
              93.865
            </div>
            <div className="items-stretch self-stretch flex justify-between gap-2.5 pr-2.5">
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                +0.208
              </div>
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                (+0.22%)
              </div>
            </div>
          </div>
          <div className="flex gap-0 pl-4 pr-2.5 py-1 border-r-zinc-200 border-r border-solid items-start">
            <div className="self-stretch flex justify-between gap-2 pr-5 items-start">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a304bbb58b1affaf5c621fa90e130fbe3548d5a54b57ed17a56c4619be316360?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-[18px] overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-white text-base font-bold self-stretch grow whitespace-nowrap">
                AUDNZD
              </div>
            </div>
            <div className="text-white text-base font-semibold mt-1">
              1.08143
            </div>
            <div className="items-stretch self-stretch flex justify-between gap-3 pr-2">
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                +0.00169
              </div>
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                (+0.16%)
              </div>
            </div>
          </div>
          <div className="flex gap-0 pl-4 py-1 border-r-zinc-200 border-r border-solid items-start">
            <div className="self-stretch flex justify-between gap-2 pr-5 items-start">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0b8b184c9aea94404fc10d92b3410a6cf5bd83cfcce15d0dc11221ab79b9bf6b?apiKey=877f25baca7641bea0898fac94c96e97&"
                className="aspect-square object-contain object-center w-[18px] overflow-hidden shrink-0 max-w-full"
              />
              <div className="text-white text-base font-bold self-stretch grow whitespace-nowrap">
                AUDSGD
              </div>
            </div>
            <div className="text-white text-base font-semibold mt-1">
              0.87400
            </div>
            <div className="items-stretch self-stretch flex justify-between gap-3">
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                +0.00247
              </div>
              <div className="justify-center text-teal-400 text-base font-medium grow whitespace-nowrap">
                (+0.28%)
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-indigo-50 self-stretch flex w-full flex-col items-stretch pl-16 pr-20 py-12 max-md:max-w-full max-md:px-5">
        <div className="mr-5 mt-14 max-md:max-w-full max-md:mr-2.5 max-md:mt-10">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[48%] max-md:w-full max-md:ml-0">
              <div className="items-stretch flex flex-col my-auto max-md:max-w-full max-md:mt-10">
                <div className="text-gray-900 text-5xl font-semibold max-md:max-w-full max-md:text-4xl">
                  What Makes FundedNext Different?{" "}
                </div>
                <div className="text-gray-800 text-opacity-80 text-xl leading-8 mt-5 max-md:max-w-full">
                  FundedNext offers no time limits in its funding challenges.
                </div>
                <div className="items-stretch flex justify-between gap-3 mt-9 max-md:max-w-full max-md:flex-wrap">
                  <div className="flex grow basis-[0%] flex-col justify-center pr-16 items-start max-md:pr-5">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1f74cde7-db48-4658-982d-641dce676085?apiKey=877f25baca7641bea0898fac94c96e97&"
                      className="aspect-[3.02] object-contain object-center w-[166px] items-start shadow-2xl overflow-hidden max-w-full"
                    />
                  </div>
                  <div className="items-stretch flex grow basis-[0%] flex-col pb-1.5">
                    <div className="text-gray-900 text-lg font-semibold leading-7">
                      Our Happy Traders
                    </div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/cddade30454c87296c4660dfdbc884a06849f3959548db9839e7f2712ca2291f?apiKey=877f25baca7641bea0898fac94c96e97&"
                      className="aspect-square object-contain object-center w-[18px] justify-center items-center overflow-hidden max-w-full self-start"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-stretch w-[26%] ml-5 max-md:w-full max-md:ml-0">
              <div className="flex flex-col items-stretch max-md:mt-5">
                <div className="bg-[linear-gradient(91deg,#3F68FF_0%,#CD63FF_100%)] flex flex-col px-5 py-8 rounded-2xl items-start max-md:px-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/76dc6295d44b3dfafea751ccab23f22d8d5bde78a78fdfd15925f90f47137057?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-[54px] overflow-hidden max-w-full"
                  />
                  <div className="self-stretch text-white text-xl font-semibold leading-7 tracking-tight mt-8">
                    15% Profit Sharing from Challenge Phase
                  </div>
                  <div className="self-stretch text-white text-base leading-7 mt-3">
                    FundedNext is the only prop firm to offer a 15% profit
                    sharing from the profit you make
                  </div>
                </div>
                <div className="bg-white flex flex-col mt-5 px-5 py-8 rounded-2xl items-start max-md:px-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/797810a59951e753b584cca3879fab4a9397501a35eb6946d15856e39c309830?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-[54px] overflow-hidden max-w-full"
                  />
                  <div className="self-stretch text-gray-900 text-xl font-semibold leading-7 tracking-tight mt-8">
                    Competitive Low Commission Rates
                  </div>
                  <div className="self-stretch text-gray-800 text-opacity-80 text-base leading-7 mt-3">
                    FundedNext offers raw spread with Swap Free: World's best
                    prop trading conditions.
                  </div>
                </div>
              </div>
            </div>{" "}
            <div className="flex flex-col items-stretch w-[26%] ml-5 max-md:w-full max-md:ml-0">
              <div className="flex grow flex-col items-stretch mt-10">
                <div className="bg-white flex flex-col px-5 py-8 rounded-2xl items-start max-md:pr-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/6224e3b818ae6ea4922afeaf8b1a1ec763d7adb487770e9bf26580b014a7176d?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-[54px] overflow-hidden max-w-full"
                  />{" "}
                  <div className="self-stretch text-gray-900 text-xl font-semibold leading-7 tracking-tight mt-8">
                    Balance Drawdown Performance Overview
                  </div>{" "}
                  <div className="self-stretch text-gray-800 text-opacity-80 text-base leading-7 mt-3">
                    Daily drawdown uses balance, not equity, for utmost prop
                    firm reliability.
                  </div>
                </div>{" "}
                <div className="bg-white flex flex-col mt-5 px-5 py-8 rounded-2xl items-start max-md:pr-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8594939bf2d867b902fc79565a5547b45453c6289aadc37f33cf925a903ad9d?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-[54px] overflow-hidden max-w-full"
                  />{" "}
                  <div className="self-stretch text-gray-900 text-xl font-semibold leading-7 tracking-tight mt-8">
                    No Time Limit on Challenge Phase
                  </div>{" "}
                  <div className="self-stretch text-gray-800 text-opacity-80 text-base leading-7 mt-3">
                    Daily drawdown uses balance, not equity, for utmost prop
                    firm reliability.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>{" "}
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a29d852efe01c03baadc09ba495ed04d99b61d47342f787be4e885d02affed3f?apiKey=877f25baca7641bea0898fac94c96e97&"
          className="aspect-[0.97] object-contain object-center w-[66px] fill-white fill-opacity-70 overflow-hidden max-w-full self-start"
        />
      </div>{" "}
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4708ae4a9dd3dedef71316a7add763e79931d39ce92651f4f4740cdc22429277?apiKey=877f25baca7641bea0898fac94c96e97&"
        className="aspect-[0.97] object-contain object-center w-[66px] fill-indigo-50 overflow-hidden max-w-full self-end"
      />{" "}
      <div className="justify-between self-center w-full max-w-[1240px] mt-14 max-md:max-w-full max-md:mt-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[48%] max-md:w-full max-md:ml-0">
            <div className="flex flex-col my-auto items-start max-md:max-w-full max-md:mt-10">
              <div className="text-gray-900 text-5xl font-semibold leading-[54px] self-stretch max-md:max-w-full max-md:text-4xl max-md:leading-[53px]">
                Introducing FundedNext Stellar Challenge 🙌
              </div>{" "}
              <div className="items-center flex gap-2 mt-7">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/9df9f733a5d74300754d83a3ecb114163be9aa1603275e3fa2e42705f0fa924f?apiKey=877f25baca7641bea0898fac94c96e97&"
                  className="aspect-square object-contain object-center w-4 fill-[linear-gradient(91deg,#3F68FF_0%,#CD63FF_100%)] overflow-hidden shrink-0 max-w-full my-auto"
                />{" "}
                <div className="text-gray-500 text-xl font-medium leading-8">
                  No Time Limit
                </div>
              </div>{" "}
              <div className="items-center self-stretch flex justify-between gap-2 mt-3 max-md:max-w-full max-md:flex-wrap">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/fcfb144f9a81faabd51b0e994a8307b79b1bd3c88cb7d3bf80606d3313053578?apiKey=877f25baca7641bea0898fac94c96e97&"
                  className="aspect-square object-contain object-center w-4 fill-[linear-gradient(91deg,#3F68FF_0%,#CD63FF_100%)] overflow-hidden shrink-0 max-w-full my-auto"
                />{" "}
                <div className="text-gray-500 text-lg font-medium leading-7 self-stretch grow shrink basis-auto max-md:max-w-full">
                  Balance Based Drawdown
                </div>
              </div>{" "}
              <div className="items-center self-stretch flex justify-between gap-2 mt-3 max-md:max-w-full max-md:flex-wrap">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/a110983251f91c67e1c2d3abe1d9f87de2c66425bc081591daffa064daf9465b?apiKey=877f25baca7641bea0898fac94c96e97&"
                  className="aspect-square object-contain object-center w-4 fill-[linear-gradient(91deg,#3F68FF_0%,#CD63FF_100%)] overflow-hidden shrink-0 max-w-full my-auto"
                />{" "}
                <div className="text-gray-500 text-xl font-medium leading-8 self-stretch grow shrink basis-auto max-md:max-w-full">
                  15% Profit Share from Challenge Phase
                </div>
              </div>{" "}
              <div className="text-white text-right text-lg font-semibold leading-6 whitespace-nowrap justify-center items-stretch bg-indigo-500 mt-10 px-5 py-4 rounded-xl">
                Learn More
              </div>
            </div>
          </div>{" "}
          <div className="flex flex-col items-stretch w-[52%] ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/58fbc69bbfb9e1555d1e3d837d92b8852e0750b7ed1e3f1644d2e73fdfb0042c?apiKey=877f25baca7641bea0898fac94c96e97&"
              className="aspect-[1.27] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-10"
            />
          </div>
        </div>
      </div>{" "}
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ea49920023fb21d5d263379afbc687ba1b4bbed4d315fced58880d5d4a12f05?apiKey=877f25baca7641bea0898fac94c96e97&"
        className="aspect-[1.03] object-contain object-center w-40 fill-indigo-50 overflow-hidden max-w-full ml-3 mt-7 self-start max-md:ml-2.5"
      />{" "}
      <div className="items-stretch bg-slate-900 self-stretch flex w-full flex-col mt-5 px-20 py-12 max-md:max-w-full max-md:px-5">
        <div className="border-b-[color:var(--Gray-600,#475467)] flex justify-between gap-5 mt-3.5 mx-8 pb-12 border-b border-solid items-start max-md:max-w-full max-md:flex-wrap max-md:mr-2.5">
          <div className="text-white text-5xl font-semibold leading-[65px] tracking-wider grow shrink basis-auto max-md:max-w-full max-md:text-4xl max-md:leading-[60px]">
            Join the Global Community for the Traders ✌️
          </div>{" "}
          <div className="justify-center items-stretch bg-indigo-500 flex gap-2.5 mt-9 p-4 rounded-xl">
            <div className="text-white text-right text-lg font-bold leading-6 grow whitespace-nowrap">
              Join our Discord
            </div>{" "}
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/da63c59e5a1b1bf43e6bf8d3d4edc6dc8aba60a355fd25bce38dff093949329c?apiKey=877f25baca7641bea0898fac94c96e97&"
              className="aspect-square object-contain object-center w-6 overflow-hidden shrink-0 max-w-full"
            />
          </div>
        </div>{" "}
        <div className="mt-16 mx-8 max-md:max-w-full max-md:mr-2.5 max-md:mt-10">
          <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
            <div className="flex flex-col items-stretch w-[28%] max-md:w-full max-md:ml-0">
              <div className="items-stretch flex flex-col max-md:mt-10">
                <div className="text-gray-200 text-base leading-6">
                  Empowering global traders with unrivalled financial support.
                  Navigate markets confidently with our innovative funding
                  models and expert guidance.
                </div>{" "}
                <div className="items-start flex justify-between gap-5 mt-8 pr-20 max-md:pr-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/2cd3e0f7dc4d2e66924efa3cf7a0ecc621cd2f18e2e377ba223064e7abde5194?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-6 overflow-hidden self-center shrink-0 max-w-full my-auto"
                  />{" "}
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/f5b33e466d7140e6177b6e9500d9679411e7f6a6e3f12a639bcc20ce8b1d9622?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-6 justify-center items-center overflow-hidden self-center shrink-0 max-w-full my-auto"
                  />{" "}
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/a729722cdb914e87a3ade3b0ad98efa92d2403e5b695a68d1443534cf463f2b7?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-6 overflow-hidden self-center shrink-0 max-w-full my-auto"
                  />{" "}
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/ec1f786f9719d336af7ebecd518be9d36e00716bbebe9462f80a9e0e941aa38d?apiKey=877f25baca7641bea0898fac94c96e97&"
                    className="aspect-square object-contain object-center w-7 overflow-hidden self-stretch shrink-0 max-w-full"
                  />
                </div>
              </div>
            </div>{" "}
            <div className="flex flex-col items-stretch w-[72%] ml-5 max-md:w-full max-md:ml-0">
              <div className="grow max-md:max-w-full max-md:mt-10">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-[33%] max-md:w-full max-md:ml-0">
                    <div className="items-stretch flex grow flex-col max-md:mt-8">
                      <div className="text-white text-lg font-extrabold leading-5 whitespace-nowrap">
                        Important Link
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-4">
                        Overview
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-3">
                        Affiliate Partner
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-3">
                        Payment Partner
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-3">
                        Success Stories
                      </div>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                    <div className="items-stretch flex flex-col pb-7 max-md:mt-8">
                      <div className="text-white text-lg font-extrabold leading-5 whitespace-nowrap">
                        Models
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-4 max-md:mr-1">
                        Express
                      </div>{" "}
                      <div className="text-gray-200 text-base font-medium leading-6 mt-3 max-md:mr-1">
                        Evaluation{" "}
                      </div>{" "}
                      <div className="items-stretch flex justify-between gap-2 mt-3 max-md:mr-1">
                        <div className="text-gray-200 text-base font-medium leading-6 grow whitespace-nowrap">
                          Stellar Challenge
                        </div>{" "}
                        <div className="text-white text-center text-xs font-medium leading-5 whitespace-nowrap items-stretch border bg-white bg-opacity-10 aspect-[1.9090909090909092] justify-center px-2 py-0.5 rounded-2xl border-solid border-white border-opacity-30 self-start">
                          New
                        </div>
                      </div>
                    </div>
                  </div>{" "}
                  <div className="flex flex-col items-stretch w-[33%] ml-5 max-md:w-full max-md:ml-0">
                    <div className="items-start flex flex-col max-md:mt-8">
                      <div className="self-stretch text-white text-lg font-extrabold leading-5 whitespace-nowrap">
                        Contact Information
                      </div>{" "}
                      <div className="items-center flex gap-2 mt-4 self-start">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc3eeef884099294a22b8b7ef04ec569b1387ec6dbea44e1e7d254fafcf048c3?apiKey=877f25baca7641bea0898fac94c96e97&"
                          className="aspect-square object-contain object-center w-5 justify-center items-center overflow-hidden shrink-0 max-w-full my-auto"
                        />{" "}
                        <div className="text-gray-200 text-base font-medium leading-6 self-stretch grow whitespace-nowrap">
                          info@wearenext.com
                        </div>
                      </div>{" "}
                      <div className="items-center flex gap-2 mt-3 self-start">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e678e3ce572b40a426adc30c535538be6b10cbcb541e92a97b5ad480670265c6?apiKey=877f25baca7641bea0898fac94c96e97&"
                          className="aspect-square object-contain object-center w-5 justify-center items-center overflow-hidden shrink-0 max-w-full my-auto"
                        />{" "}
                        <div className="text-gray-200 text-base font-medium leading-6">
                          +986 8989 899
                        </div>
                      </div>{" "}
                      <div className="items-center flex gap-2 mt-3 self-start">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e678e3ce572b40a426adc30c535538be6b10cbcb541e92a97b5ad480670265c6?apiKey=877f25baca7641bea0898fac94c96e97&"
                          className="aspect-square object-contain object-center w-5 justify-center items-center overflow-hidden shrink-0 max-w-full my-auto"
                        />{" "}
                        <div className="text-gray-200 text-base font-medium leading-6">
                          +986 8989 899
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>{" "}
        <div className="items-stretch border-t-[color:var(--Gray-600,#475467)] flex justify-between gap-5 mt-16 pt-8 border-t border-solid max-md:max-w-full max-md:flex-wrap max-md:mt-10">
          <div className="text-gray-300 text-base leading-6 grow max-md:max-w-full">
            © 2023 alll rights reserved.
          </div>{" "}
          <div className="items-stretch flex gap-5">
            <div className="text-gray-200 text-base font-medium leading-6 grow whitespace-nowrap">
              Cookie Policy
            </div>{" "}
            <div className="text-gray-200 text-base font-medium leading-6">
              Privacy Policy
            </div>{" "}
            <div className="text-gray-200 text-base font-medium leading-6 grow whitespace-nowrap">
              Terms & Conditions
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
